---

api:
  build: .
  dockerfile: ./api/Dockerfile
  env_file: 
    - ./api/.env
  command: python -m flask run
  volumes:
    - ./api:/app
  ports:
    - "5000:5000"
  links:
    - rabbitmq

rabbitmq:
  image: rabbitmq:3-management
  container_name: que
  ports:
    - "5672:5672"
    - "8080:15672"